import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List, Dict, Any

from app.config import settings

logger = logging.getLogger(__name__)


class EmailService:
    """SMTP email service for meeting summaries."""
    
    def __init__(self):
        self.smtp_host = settings.SMTP_HOST
        self.smtp_port = settings.SMTP_PORT
        self.smtp_user = settings.SMTP_USER
        self.smtp_password = settings.SMTP_PASSWORD
        self.from_email = settings.SMTP_FROM_EMAIL
        self.use_tls = settings.SMTP_USE_TLS
    
    def _format_summary_html(self, meeting_id: str, summary: Dict[str, Any]) -> str:
        """Format summary as HTML email."""
        html = f"""
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                h1 {{ color: #2c3e50; }}
                h2 {{ color: #34495e; margin-top: 20px; }}
                .overview {{ background-color: #ecf0f1; padding: 15px; border-radius: 5px; margin: 15px 0; }}
                ul {{ padding-left: 20px; }}
                li {{ margin: 8px 0; }}
                .footer {{ margin-top: 30px; padding-top: 20px; border-top: 1px solid #bdc3c7; color: #7f8c8d; font-size: 12px; }}
            </style>
        </head>
        <body>
            <h1>Meeting Summary</h1>
            <p><strong>Meeting ID:</strong> {meeting_id}</p>
            
            <div class="overview">
                <h2>Overview</h2>
                <p>{summary.get('overview', 'No overview available')}</p>
            </div>
            
            <h2>Key Points</h2>
            <ul>
        """
        
        for point in summary.get('key_points', []):
            html += f"<li>{point}</li>\n"
        
        html += """
            </ul>
            
            <h2>Decisions Made</h2>
            <ul>
        """
        
        for decision in summary.get('decisions', []):
            html += f"<li>{decision}</li>\n"
        
        html += """
            </ul>
            
            <h2>Action Items</h2>
            <ul>
        """
        
        for action in summary.get('action_items', []):
            html += f"<li>{action}</li>\n"
        
        html += """
            </ul>
            
            <div class="footer">
                <p>This summary was automatically generated by the Meeting Agent system.</p>
            </div>
        </body>
        </html>
        """
        
        return html
    
    async def send_summary(self, meeting_id: str, summary: Dict[str, Any], recipients: List[str]) -> bool:
        """
        Send meeting summary via email.
        
        Args:
            meeting_id: Meeting identifier
            summary: Structured summary
            recipients: List of email addresses
        
        Returns:
            True if successful
        """
        if not recipients:
            logger.warning("No recipients provided")
            return False
        
        try:
            # Create message
            msg = MIMEMultipart('alternative')
            msg['Subject'] = f"Meeting Summary - {meeting_id}"
            msg['From'] = self.from_email
            msg['To'] = ', '.join(recipients)
            
            # Create HTML content
            html_content = self._format_summary_html(meeting_id, summary)
            html_part = MIMEText(html_content, 'html')
            msg.attach(html_part)
            
            # Send email
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                if self.use_tls:
                    server.starttls()
                server.login(self.smtp_user, self.smtp_password)
                server.send_message(msg)
            
            logger.info(f"Sent summary email for {meeting_id} to {len(recipients)} recipients")
            return True
            
        except Exception as e:
            logger.error(f"Email send error: {e}", exc_info=True)
            return False


email_service = EmailService()